// src/ui/BookList.tsx
import { useUserBooks } from "@hooks/books"
import { Book } from "@ui/Book"
import * as React from "react"
import { HardcoverParams } from "@/main"

interface BookListProps {
  className?: string
  params: HardcoverParams
}

export const BookList: React.FC<BookListProps> = ({ className, params }) => {
  const {
    data: userBooks = [],
    isLoading,
    isError,
    error,
    refetch,
    isRefetching,
  } = useUserBooks({
    limit: params.limit,
    status: params.status,
  })

  const onRefetch = async () => {
    await refetch()
  }

  if (isLoading) {
    return (
      <div className={`hardcover-loading ${className || ""}`}>
        <div className="hardcover-loading-container">
          <div className="spinner" />
          <div className="hardcover-loading-text">Loading your books...</div>
        </div>
      </div>
    )
  }

  if (isError) {
    return (
      <div className={`hardcover-error ${className || ""}`}>
        <div className="hardcover-error-container">
          <div className="hardcover-error-title">❌ Failed to load books</div>
          <div className="hardcover-error-message">
            {error instanceof Error ? error.message : "Unknown error occurred"}
          </div>
          <button
            className="hardcover-error-retry"
            onClick={onRefetch}
            type="button">
            Retry
          </button>
        </div>
      </div>
    )
  }

  if (userBooks.length === 0) {
    return (
      <div className={`hardcover-empty ${className || ""}`}>
        <div className="hardcover-empty-container">
          <div className="hardcover-empty-icon">📚</div>
          <div className="hardcover-empty-title">
            No books currently reading
          </div>
          <div className="hardcover-empty-subtitle">
            Start reading a book in Hardcover to see it here
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className={`hardcover-book-list ${className || ""}`}>
      {userBooks.map((userBook) => (
        <Book key={userBook.book.id} userBook={userBook} />
      ))}
      <button
        disabled={isLoading || isRefetching}
        onClick={onRefetch}
        type="button">
        {isRefetching ? "⟳" : "↻"}
      </button>
    </div>
  )
}

// src/ui/BookList.svelte
<script lang="ts">
  import {
    createUpdateProgressStore,
    createUserBooksStore,
  } from "@stores/books"
  import Book from "@ui/Book.svelte"
  import { onDestroy } from "svelte"
  import { HardcoverParams } from "@/main"
  import { UserBook } from "@/types"

  export let className: string = ""
  export let params: HardcoverParams

  let userBooksData: UserBook[] = []
  let loadingData = true
  let errorData: Error | null = null
  let refetchingData = false

  const userBooksStore = createUserBooksStore(params.limit, params.status)
  userBooksStore.fetch()

  const updateProgressStore = createUpdateProgressStore(() =>
    userBooksStore.refetch(),
  )

  const unsubscribe = userBooksStore.subscribe((state) => {
    userBooksData = state.data ?? []
    loadingData = state.isLoading
    errorData = state.error
    refetchingData = state.isRefetching
  })

  onDestroy(() => {
    unsubscribe()
  })

  async function onRefetch() {
    await userBooksStore.refetch()
  }
</script>

{#if loadingData}
    <div class={`hardcover-loading ${className || ""}`}>
        <div class="hardcover-loading-container">
            <div class="spinner"></div>
            <div class="hardcover-loading-text">Loading your books...</div>
        </div>
    </div>
{:else if errorData}
    <div class={`hardcover-error ${className || ""}`}>
        <div class="hardcover-error-container">
            <div class="hardcover-error-title">❌ Failed to load books</div>
            <div class="hardcover-error-message">
                {errorData?.message || "Unknown error occurred"}
            </div>
            <button
                class="hardcover-error-retry"
                on:click={onRefetch}
                type="button"
            >
                Retry
            </button>
        </div>
    </div>
{:else if userBooksData.length === 0}
    <div class={`hardcover-empty ${className || ""}`}>
        <div class="hardcover-empty-container">
            <div class="hardcover-empty-icon">📚</div>
            <div class="hardcover-empty-title">No books currently reading</div>
            <div class="hardcover-empty-subtitle">
                Start reading a book in Hardcover to see it here
            </div>
        </div>
    </div>
{:else}
    <div class={`hardcover-book-list ${className || ""}`}>
        {#each userBooksData as userBook (userBook?.book?.id || Math.random())}
            {@const bookId = userBook?.book?.id}
            {#if bookId}
                <Book {userBook} {updateProgressStore} />
            {/if}
        {/each}
        <button
            disabled={loadingData || refetchingData}
            on:click={onRefetch}
            type="button"
        >
            {refetchingData ? "⟳" : "↻"}
        </button>
    </div>
{/if}
